server:
  port: 9191


spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        filters:
          - name: CircuitBreaker
            args:
              name: USER-SERVICE
              fallbackuri: forward:/user-service-fallback



      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/departments/**

        filters:
          - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/depart-service-fallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000



management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream
